SEARCH_DIR(.\)
SEARCH_DIR(C:\lazarus\lcl\units\aarch64-android\customdrawn\)
SEARCH_DIR(C:\lazarus\lcl\units\aarch64-android\)
SEARCH_DIR(C:\lazarus\components\lazutils\lib\aarch64-android\)
SEARCH_DIR(C:\lazarus\components\freetype\lib\aarch64-android\)
SEARCH_DIR(C:\lazarus\packager\units\aarch64-android\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\httpd22\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\zlib\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\webidl\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\vcl-compat\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\unzip\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\tplylib\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\tcl\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\symbolic\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\sqlite\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-unicode\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-objpas\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-generics\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-extra\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-console\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\regexpr\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\pthreads\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\postgres\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\pcap\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\pastojs\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\oracle\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\openssl\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\odbc\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\numlib\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\mysql\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\libtar\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\libpng\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\libmicrohttpd\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\libmagic\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\libgd\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\libenet\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\jni\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\imagemagick\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\ibase\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\httpd24\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\hermes\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\hash\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\gnutls\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\gdbm\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fppkg\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fpmkunit\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fftw\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-xml\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-web\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-stl\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-sound\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-sdo\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-res\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-registry\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-process\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-pdf\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-passrc\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-net\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-json\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-js\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-fpcunit\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-extra\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-db\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-async\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\fastcgi\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\dblib\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\chm\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\bzip2\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\units\aarch64-android\)
SEARCH_DIR(C:\lazarus\fpc\3.2.2\bin\x86_64-win64\)
VERSION
{
  {
    global:
      JNI_OnLoad;
      JNI_OnUnload;
    local:
      *;
  };
}
INPUT(
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\dllprt0.o
crtbegin_so.o
"d:\Projetos AntiGravity\LazarusAndroid\demo2\lib\aarch64-android\project1.o"
"d:\Projetos AntiGravity\LazarusAndroid\demo2\lib\aarch64-android\project1.or"
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\system.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\lnfodwrf.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\exeinfo.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\strings.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\fpintres.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\objpas.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\cthreads.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\sysutils.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnint.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\interfaces.o
C:\lazarus\lcl\units\aarch64-android\forms.o
C:\lazarus\lcl\units\aarch64-android\customdrawn_android.o
C:\lazarus\lcl\units\aarch64-android\customdrawndrawers.o
"d:\Projetos AntiGravity\LazarusAndroid\demo2\lib\aarch64-android\unit1.o"
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\baseunix.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\unix.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\unixtype.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\initc.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\unixutil.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\ctypes.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\errors.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\sysconst.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\dl.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\types.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\classes.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\math.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpimage.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpcanvas.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpimgcanv.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-objpas\dateutils.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-xml\xmlread.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-xml\dom.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawn_androidproc.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\jni.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\bitmap.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\log.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\keycodes.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazfileutils.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazutf8.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnproc.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnthemes.o
C:\lazarus\lcl\units\aarch64-android\customdrawn_common.o
C:\lazarus\lcl\units\aarch64-android\customdrawncontrols.o
C:\lazarus\lcl\units\aarch64-android\lazcanvas.o
C:\lazarus\lcl\units\aarch64-android\lazregions.o
C:\lazarus\lcl\units\aarch64-android\lazdeviceapis.o
C:\lazarus\lcl\units\aarch64-android\lclplatformdef.o
C:\lazarus\lcl\units\aarch64-android\interfacebase.o
C:\lazarus\lcl\units\aarch64-android\themes.o
C:\lazarus\lcl\units\aarch64-android\dialogs.o
C:\lazarus\lcl\units\aarch64-android\buttons.o
C:\lazarus\lcl\units\aarch64-android\controls.o
C:\lazarus\lcl\units\aarch64-android\lclproc.o
C:\lazarus\lcl\units\aarch64-android\intfgraphics.o
C:\lazarus\components\lazutils\lib\aarch64-android\graphtype.o
C:\lazarus\lcl\units\aarch64-android\lcltype.o
C:\lazarus\lcl\units\aarch64-android\lmessages.o
C:\lazarus\lcl\units\aarch64-android\graphics.o
C:\lazarus\lcl\units\aarch64-android\lclstrconsts.o
C:\lazarus\lcl\units\aarch64-android\menus.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazloggerbase.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\typinfo.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\rtlconsts.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\clipping.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fppixlcanv.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\pixtools.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\ellipses.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-xml\xmlutils.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-xml\xmlreader.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-xml\xmltextreader.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-xml\dtdmodel.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\uriparser.o
C:\lazarus\lcl\units\aarch64-android\lclmessageglue.o
C:\lazarus\lcl\units\aarch64-android\wscontrols.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpreadbmp.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpwritebmp.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\bmpcomn.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpreadpng.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpwritepng.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpreadtiff.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpwritetiff.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fptiffcmn.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\avl_tree.o
C:\lazarus\components\lazutils\lib\aarch64-android\fpcadds.o
C:\lazarus\components\lazutils\lib\aarch64-android\laztracer.o
C:\lazarus\lcl\units\aarch64-android\lclversion.o
C:\lazarus\lcl\units\aarch64-android\icnstypes.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpimgcmn.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\pngcomn.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\zstream.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\zbase.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\gzio.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\hash\crc.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\zdeflate.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\zinflate.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\trees.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\adler.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\infblock.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\infutil.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\infcodes.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\inftrees.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\paszlib\inffast.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazclasses.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazmethodlist.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\cwstring.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-objpas\strutils.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\dynlibs.o
C:\lazarus\components\lazutils\lib\aarch64-android\translations.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-json\jsonscanner.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-json\jsonparser.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-json\fpjson.o
C:\lazarus\components\lazutils\lib\aarch64-android\fileutil.o
C:\lazarus\components\lazutils\lib\aarch64-android\lconvencoding.o
C:\lazarus\components\lazutils\lib\aarch64-android\avglvltree.o
C:\lazarus\components\lazutils\lib\aarch64-android\stringhashlist.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-json\jsonreader.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-objpas\variants.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\contnrs.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-objpas\varutils.o
C:\lazarus\components\lazutils\lib\aarch64-android\masks.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazutilsstrconsts.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\dos.o
C:\lazarus\components\lazutils\lib\aarch64-android\codepagescommon.o
C:\lazarus\components\lazutils\lib\aarch64-android\codepagesasian.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazdbglog.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazutilities.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl-objpas\system.uitypes.o
C:\lazarus\lcl\units\aarch64-android\wsreferences.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazversion.o
C:\lazarus\lcl\units\aarch64-android\lclintf.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpreadpnm.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpwritepnm.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpreadjpeg.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpwritejpeg.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-image\fpreadgif.o
C:\lazarus\lcl\units\aarch64-android\lresources.o
C:\lazarus\lcl\units\aarch64-android\lclrescache.o
C:\lazarus\components\lazutils\lib\aarch64-android\graphmath.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jpeglib.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdapimin.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdatasrc.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdapistd.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jmorecfg.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdeferr.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jinclude.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jerror.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jmemmgr.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdmarker.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdinput.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcomapi.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jutils.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jmemnobs.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdmaster.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdcolor.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdsample.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdpostct.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jddctmgr.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdphuff.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdhuff.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdcoefct.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdmainct.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jquant1.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jquant2.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdmerge.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdct.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jidctfst.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jidctint.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jidctflt.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jidctred.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcapistd.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcapimin.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jdatadst.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcparam.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcinit.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcmarker.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcphuff.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jchuff.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcmaster.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jccolor.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcsample.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcprepct.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcdctmgr.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jccoefct.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jcmainct.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jfdctint.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jfdctfst.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\pasjpeg\jfdctflt.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazutf16.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazconfigstorage.o
C:\lazarus\components\lazutils\lib\aarch64-android\dynqueue.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazstringutils.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\syncobjs.o
C:\lazarus\components\lazutils\lib\aarch64-android\utf8process.o
C:\lazarus\components\lazutils\lib\aarch64-android\lazsysutils.o
C:\lazarus\components\lazutils\lib\aarch64-android\maps.o
C:\lazarus\components\lazutils\lib\aarch64-android\integerlist.o
C:\lazarus\lcl\units\aarch64-android\tmschema.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\fgl.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-process\process.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-process\pipes.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\rtl\termio.o
C:\lazarus\lcl\units\aarch64-android\imglist.o
C:\lazarus\lcl\units\aarch64-android\propertystorage.o
C:\lazarus\lcl\units\aarch64-android\actnlist.o
C:\lazarus\lcl\units\aarch64-android\lclclasses.o
C:\lazarus\lcl\units\aarch64-android\wslclclasses.o
C:\lazarus\lcl\units\aarch64-android\wsimglist.o
C:\lazarus\lcl\units\aarch64-android\wsproc.o
C:\lazarus\lcl\units\aarch64-android\wsfactory.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\rttiutils.o
C:\lazarus\lcl\units\aarch64-android\wsmenus.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\custapp.o
C:\lazarus\lcl\units\aarch64-android\customtimer.o
C:\lazarus\lcl\units\aarch64-android\clipbrd.o
C:\lazarus\lcl\units\aarch64-android\helpintfs.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\fcl-base\singleinstance.o
C:\lazarus\fpc\3.2.2\units\aarch64-android\chm\fasthtmlparser.o
C:\lazarus\lcl\units\aarch64-android\wsforms.o
C:\lazarus\lcl\units\aarch64-android\stdctrls.o
C:\lazarus\lcl\units\aarch64-android\extctrls.o
C:\lazarus\lcl\units\aarch64-android\comctrls.o
C:\lazarus\lcl\units\aarch64-android\toolwin.o
C:\lazarus\components\lazutils\lib\aarch64-android\textstrings.o
C:\lazarus\components\lazutils\lib\aarch64-android\extendedstrings.o
C:\lazarus\lcl\units\aarch64-android\wsstdctrls.o
C:\lazarus\lcl\units\aarch64-android\popupnotifier.o
C:\lazarus\lcl\units\aarch64-android\wsextctrls.o
C:\lazarus\lcl\units\aarch64-android\imagelistcache.o
C:\lazarus\lcl\units\aarch64-android\wsbuttons.o
C:\lazarus\lcl\units\aarch64-android\wscomctrls.o
C:\lazarus\lcl\units\aarch64-android\wstoolwin.o
C:\lazarus\lcl\units\aarch64-android\messages.o
C:\lazarus\lcl\units\aarch64-android\wslazdeviceapis.o
C:\lazarus\lcl\units\aarch64-android\buttonpanel.o
C:\lazarus\lcl\units\aarch64-android\dialogres.o
C:\lazarus\lcl\units\aarch64-android\wsdialogs.o
C:\lazarus\lcl\units\aarch64-android\taskdlgemulation.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwsfactory.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwsforms.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnprivate.o
C:\lazarus\lcl\units\aarch64-android\calendar.o
C:\lazarus\lcl\units\aarch64-android\spin.o
C:\lazarus\lcl\units\aarch64-android\wscalendar.o
C:\lazarus\lcl\units\aarch64-android\wsspin.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwsbuttons.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwscomctrls.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwscontrols.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwsextctrls.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwsmenus.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwsspin.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwsstdctrls.o
C:\lazarus\lcl\units\aarch64-android\customdrawn\customdrawnwslazdeviceapis.o
)
INPUT(
-llog
-lc
-ldl
-ljnigraphics
)
GROUP(
-lc
)
INPUT(
crtend_so.o
)
SECTIONS
{
  .data           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
}
INSERT AFTER .data1
FPC_JNI_ON_LOAD = CUSTOMDRAWNINT_$$_JNI_ONLOAD$PJAVAVM$POINTER$$LONGINT;
FPC_LIB_MAIN_ANDROID = FPC_JNI_LIB_MAIN_ANDROID;
